language: java
jdk:
  - oraclejdk11
  - openjdk11
before_install:
  - git clone https://github.com/CaoYnag/spes.git spes; cd spes; mvn install -DskipTests=true; cd ..;
script:
  - mvn install -DskipTests=true
